MarshallsLLCSystem/Presentacion.MarshallsLLCWebApp/Models/SalaryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Presentacion.MarshallsLLCWebApp.Models
{
    public class SalaryViewModel
    {
        public int Id { get; set; }
        public int IdEmployee { get; set; }
        public string IdentificationNumber { get; set; }
        public decimal BaseSalary { get; set; }
        public decimal ProductionBonus { get; set; }
        public decimal CompensationBonus { get; set; }
        public decimal Commission { get; set; }
        public decimal Contributions { get; set; }
        public decimal TotalSalary { get; set; }
        public int PayYear { get; set; }
        public int PayMonth { get; set; }
        public int PayDay { get; set; }
    }
}

MarshallsLLCSystem/Presentacion.MarshallsLLCWebApp/Controllers/SalaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Presentacion.MarshallsLLCWebApp.Models;
using Aplicacion.Dto;
using Dominio.Model.Entities;
using Dominio.Model.ObjectValues;
using System.Data.SqlClient;
using System.Data;
using System.Text.RegularExpressions;

namespace Presentacion.MarshallsLLCWebApp.Controllers
{
    public class SalaryController : Controller
    {
        private SalaryService salaryService = new SalaryService();
        private OfficeService officeService = new OfficeService();
        private DivisionsService divisionsService = new DivisionsService();
        private PositionsService positionsService = new PositionsService();

        private Salary salary = new Salary();
        private CalculoSalario calculoSalario = new CalculoSalario();
        private GetActualDate getActualDate = new GetActualDate();
        private ConsultaSalaryModel consultaSalaryModel = new ConsultaSalaryModel();
        private ItemsBuscarPor itemsBuscarPor = new ItemsBuscarPor();

        //Codigos para mostrar la lista de los empleados a los que se les va a procesar los pagos salariales
        public ActionResult GetEmployeeAllForPay(string txtBuscarPor = "")
        {
            
            var employeList = new EmployeeService().GetEmployees();
            List<EmployeeViewModel> viewModels = new List<EmployeeViewModel>();
            if (txtBuscarPor == "")
            {

                foreach (Employee item in employeList)
                {
                    viewModels.Add(new EmployeeViewModel
                    {
                        Id = item.Id,
                        Office = item.Office,
                        EmployeeCode = item.EmployeeCode,
                        EmployeeName = item.EmployeeName,
                        EmployeeSurname = item.EmployeeSurname,
                        Division = item.Division,
                        Position = item.Position,
                        Grade = item.Grade,
                        BeginDate = item.BeginDate,
                        Birthday = item.Birthday,
                        IdentificationNumber = item.IdentificationNumber,
                        BaseSalary = item.BaseSalary,
                        ProductionBonus = item.ProductionBonus,
                        CompensationBonus = item.CompensationBonus,
                        Commission = item.Commission,
                        Contributions = item.Contributions

                    });
                }
                return View(viewModels);
            }
            
            if (txtBuscarPor != "")
            {
                if (Regex.IsMatch(txtBuscarPor, @"^[0-9]+$"))
                {
                    var employeListId = new SalaryService().BuscEmpID(Convert.ToInt32(txtBuscarPor));
                    
                    List<EmployeeViewModel> employeeViewModel = new List<EmployeeViewModel>();

                    foreach (Employee item in employeListId)
                    {
                        employeeViewModel.Add(new EmployeeViewModel
                        {
                            Id = item.Id,
                            Office = item.Office,
                            EmployeeCode = item.EmployeeCode,
                            EmployeeName = item.EmployeeName,
                            EmployeeSurname = item.EmployeeSurname,
                            Division = item.Division,
                            Position = item.Position,
                            Grade = item.Grade,
                            BeginDate = item.BeginDate,
                            Birthday = item.Birthday,
                            IdentificationNumber = item.IdentificationNumber,
                            BaseSalary = item.BaseSalary,
                            ProductionBonus = item.ProductionBonus,
                            CompensationBonus = item.CompensationBonus,
                            Commission = item.Commission,
                            Contributions = item.Contributions

                        });
                    }

                    return View(employeeViewModel);
                }
                else
                {
                    List<EmployeeViewModel> viewModelsList = new List<EmployeeViewModel>();
                    return View(viewModelsList);
                }

            }
            try
            {
                


            }
            catch (Exception)
            {
                return View();
            }
            return View(viewModels);
        }

        //Codigos para cargar los datos del empleado en la vista
        [HttpGet]
        public ActionResult AddSalary(int id)
        {
            
            try
            {
                var employeList = new SalaryService().BuscEmpID(id);

                SalaryViewModel salaryViewModel = new SalaryViewModel();

                foreach (Employee item in employeList)
                {
                    salaryViewModel.IdEmployee = item.Id;
                    salaryViewModel.IdentificationNumber = item.IdentificationNumber;
                    salaryViewModel.BaseSalary = item.BaseSalary;
                    salaryViewModel.ProductionBonus = item.ProductionBonus;
                    salaryViewModel.CompensationBonus = item.CompensationBonus;
                    salaryViewModel.Commission = item.Commission;
                    salaryViewModel.Contributions = item.Contributions;
                    salaryViewModel.TotalSalary = calculoSalario.CalcluloTotalSalary(item.BaseSalary, item.ProductionBonus, item.CompensationBonus, item.Commission, item.Contributions);
                }

                return View(salaryViewModel);
            }
            catch (Exception)
            {
                return View();
            }
            
        }
        
        //Codigos para registrar el salario al empleado selecionado
        [HttpPost]
        public ActionResult AddSalary(List<SalaryViewModel> ListaPagoSalario)
        {
            try
            {
                string mensaje = "";
                string validacion = "";
                //Validacion para cofirmar los meses pagos de los empleados
                List<Salary> ListSalary = new List<Salary>();
                foreach (var data in ListaPagoSalario)
                {
                    salary.IdEmployee = Convert.ToInt32(data.IdEmployee);
                    salary.PayYear = Convert.ToInt32(data.PayYear);
                    salary.PayMonth = Convert.ToInt32(data.PayMonth);

                    ListSalary.Add(salary);
                    validacion = salaryService.ValidarPagoMes(ListSalary);
                    if (validacion != "Ninguno")
                    {
                        return Json(validacion);
                    }
                }
                
                //Codigos para registrar los pagos a los empleados
                if (validacion == "Ninguno")
                {
                    foreach (var data in ListaPagoSalario)
                    {
                        salary.IdEmployee = Convert.ToInt32(data.IdEmployee);
                        salary.IdentificationNumber = data.IdentificationNumber;
                        salary.BaseSalary = Convert.ToDecimal(data.BaseSalary);
                        salary.ProductionBonus = Convert.ToDecimal(data.ProductionBonus);
                        salary.CompensationBonus = Convert.ToDecimal(data.CompensationBonus);
                        salary.Commission = Convert.ToDecimal(data.Commission);
                        salary.Contributions = Convert.ToDecimal(data.Contributions);
                        salary.TotalSalary = Convert.ToDecimal(data.TotalSalary);
                        salary.PayYear = Convert.ToInt32(data.PayYear);
                        salary.PayMonth = Convert.ToInt32(data.PayMonth);
                        salary.PayDay = getActualDate.GetActualDay();

                        salaryService.AddSalary(salary);
                        mensaje = "Proceso realizado";


                    }

                }
                else
                {
                    return Json(validacion);
                }


                return Json(mensaje);

            }
            catch (Exception ex)
            {
                return Json("Error! " + ex.Message);
            }
            
            
        }

        //Cargar Lista de salarios pagos
        public ActionResult GetSalaryList(string BuscarPorList = "", string txtBuscarPor = "",string DDLYear = "",string DDLMonth = "")
        {
            
            ViewBag.OfficesList = new SelectList(officeService.OfficesList(), "NameOffices", "NameOffices");
            ViewBag.PosicionList = new SelectList(divisionsService.DivisionsList(), "NameDivisions", "NameDivisions");
            ViewBag.DivisionList = new SelectList(positionsService.PositionsList(), "NamePositions", "NamePositions");
            ViewBag.BuscarPorList = new SelectList(itemsBuscarPor.ListaItems(), "BuscarPor", "BuscarPor");
            ViewBag.DDLYear = new SelectList(getActualDate.GetListYear(), "ListYears", "ListYears");
            ViewBag.DDLMonth = new SelectList(getActualDate.GetListMonth(), "ListMonths", "ListMonths");
            if (DDLYear == "")
            {
                DDLYear = getActualDate.GetActualYear().ToString();
            }
            if (DDLMonth == "")
            {
                DDLMonth = getActualDate.GetActualMonth().ToString();
            }

            if (BuscarPorList == "" || BuscarPorList == "Todos" && txtBuscarPor == "")
            {
                var salaryList = new SalaryService().GetSalaryYearAndMonth(Convert.ToInt32(DDLYear), Convert.ToInt32(DDLMonth));
                List<ConsultaSalaryViewModel> viewModels = new List<ConsultaSalaryViewModel>();

                foreach (ConsultaSalaryModel item in salaryList)

MarshallsLLCSystem/Presentacion.MarshallsLLCWebApp/Views/Salary/GetAdvancedSalaryList.cshtml
@model IEnumerable<Presentacion.MarshallsLLCWebApp.Models.ConsultaSalaryViewModel>

@{
    ViewBag.Title = "GetAdvancedSalaryList";
}

<div class="panel panel-default">
    <div class="panel-heading" style="background:#2C3E50; color:#ffffff;"><h2 style="text-align:center; font-family:Arial; font-weight:700;">Busqueda Avanzada de Salarios</h2></div>
    <div class="panel-body">
        @using (Html.BeginForm("GetAdvancedSalaryList", "Salary", FormMethod.Post))
        {
            <div class="form-horizontal">
                <fieldset>
                    <div class="row" style="padding-bottom:8px;">
                        <div class="form-inline col-md-6">
                            @Html.Label("Id Empleado:", new { @class = "control-label col-md-4" })

                            <div class="col-md-15">
                                @Html.TextBox("txtBuscId", null, new { @class = "form-control" })
                                <input type="submit" id="btnBuscarSalary" value="Buscar" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                    <br />
                    <div>
                        <div class="row">
                            <div class="col-md-3 col-sm-3 col-xs-3">
                            <p><span style="font-weight:bold">Nombre:</span> @ViewBag.Nombre</p>
                            <p><span style="font-weight:bold">NumeroIdentificacion:</span> @ViewBag.NumeroIdentificacion</p>
                            <p><span style="font-weight:bold">Office:</span> @ViewBag.Office</p>
                        </div>
                         <div class="col-md-3 col-sm-3 col-xs-3">
                            <p><span style="font-weight:bold">Position:</span> @ViewBag.Position</p>
                            <p><span style="font-weight:bold">Grade:</span> @ViewBag.Grade</p>
                         </div>
                        </div>
                    </div>
                    <br />
                    <div class="row" style="padding-bottom:8px;">
                        <div class="form-inline col-md-6">
                            @Html.Label("Ultimos Salarios de:", new { @class = "control-label col-md-4" })
                            <div class="col-md-5 ">
                                @Html.DropDownList("DDBuscarPorMeses", null, "Seleccione", new { @class = "form-control", onchange = "this.form.submit()" })
                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>
        }
    </div>
</div>

<h2>Lista de Empleados</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmployeeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmployeeSurname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdentificationNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalSalary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PayMonth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PayYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bono)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmployeeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmployeeSurname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdentificationNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalSalary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PayMonth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PayYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bono)
            </td>

        </tr>
    }

</table>


<script type="text/javascript">
    var selectDDBuscarPorMeses = document.getElementById("DDBuscarPorMeses");
    selectDDBuscarPorMeses.value = "3 meses consecutivos";

</script>

MarshallsLLCSystem/Presentacion.MarshallsLLCWebApp/Views/Salary/GetEmployeeAllForPay.cshtml
@model IEnumerable<Presentacion.MarshallsLLCWebApp.Models.EmployeeViewModel>

@{
    ViewBag.Title = "GetEmployeeAllForPay";
}

<div class="panel panel-default">
    <div class="panel-heading" style="background:#2C3E50; color:#ffffff;"><h2 style="text-align:center; font-family:Arial; font-weight:700;">Realizar Pagos de Salarios</h2></div>
    <div class="panel-body">
        @using (Html.BeginForm("GetEmployeeAllForPay", "Salary", FormMethod.Post))
        {
            <div class="form-horizontal">
                <fieldset>
                    <div class="row" style="padding-bottom:8px;">
                        <div class="row" style="padding-bottom:8px;">
                            <div class="form-inline col-md-6">
                                @Html.Label("Id Empleado:", new { @class = "control-label col-md-4" })
                                <div class="col-md-15">
                                    @Html.TextBox("txtBuscarPor", null, new { @class = "form-control" })
                                    <input type="submit" value="Buscar" id="btnBuscar" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>
        }
    </div>
</div>

<h2>Lista de Empleados</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EmployeeCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmployeeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmployeeSurname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Division)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Position)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdentificationNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BaseSalary)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EmployeeCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmployeeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmployeeSurname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Division)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Position)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdentificationNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BaseSalary)
        </td>
        
        <td>
            @Html.ActionLink("Procesar Pago", "AddSalary", new { id=item.Id }, htmlAttributes: new { @id = "linkProcesarPago" })
    </tr>
}

</table>

MarshallsLLCSystem/Presentacion.MarshallsLLCWebApp/Views/Salary/GetSalaryList.cshtml
@model IEnumerable<Presentacion.MarshallsLLCWebApp.Models.ConsultaSalaryViewModel>

@{
    ViewBag.Title = "GetSalaryList";
}

<div class="panel panel-default">
    <div class="panel-heading" style="background:#2C3E50; color:#ffffff;"><h2 style="text-align:center; font-family:Arial; font-weight:700;">Buscar Pagos de Salarios</h2></div>
    <div class="panel-body">
        @using (Html.BeginForm("GetSalaryList","Salary", FormMethod.Post))
        {
            <div class="form-horizontal">
                <fieldset>
                    <div class="row" style="padding-bottom:8px;">
                        <div class="form-inline form-group col-md-5">
                            @Html.Label("Fecha:", new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.DropDownList("DDLYear", null, "", new { @class = "form-control" })
                            </div>
                            @Html.Label("Mes:", new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.DropDownList("DDLMonth", null, "", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-inline col-md-15">
                            <a href="~/Salary/GetAdvancedSalaryList">
                                <input type="button" value="Busqueda Avanzada" class="btn btn-default" />
                            </a>
                        </div>
                        
                        <div class="form-inline col-md-10">
                            @Html.Label("Buscar Por:", new { @class = "control-label col-md-4" })
                            <div class="col-md-3 dropdown">
                                @Html.DropDownList("BuscarPorList", null, "Seleccione", new { @class = "form-control", onkeypress = "return check(event)" })
                            </div>
                            <div class="col-md-15">
                                @Html.TextBox("txtBuscarPor", null, new { @class = "form-control" })
                                <input type="submit" value="Buscar" class="btn btn-default"  />
                            </div>
                            
                        </div>

                    </div>
                </fieldset>
            </div>
        }
    </div>
</div>

<h2>Lista de Pagos de Salarios</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdEmployee)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmployeeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmployeeSurname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Division)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Position)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BeginDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Birthday)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdentificationNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalSalary)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmployeeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmployeeSurname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Division)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Position)
        </td>
        <td>
            @item.BeginDate.ToShortDateString()
        </td>
        <td>
            @item.Birthday.ToShortDateString()
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdentificationNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalSalary)
        </td>
        
    </tr>
}

</table>

<script type="text/javascript">
    var fecha = new Date();
    var yearActual = fecha.getFullYear();
    var monthAcctual = fecha.getMonth()+1;

    var selectDDLYear = document.getElementById("DDLYear");
    selectDDLYear.value = yearActual;

    var selectDDLMonth = document.getElementById("DDLMonth");
    selectDDLMonth.value = monthAcctual;

    var selectBuscarPorList = document.getElementById("BuscarPorList");

    var txtBuscarPor = document.getElementById("txtBuscarPor");

 

</script>